### ISSUE TITLE
develop Country specific commission to work per commission group

### ISSUE THREAD

**Issue by lnikodem** [QualityUnit/pap-public#20]
new country specific commissions work per commission type, improve them to work per commission group

SJJ-HXHIQ-265

**Comment by msvitek** [comment]
the main problem is that if you enable it in one of the groups and set some commission there then it is also enabled in other groups but with no commission defined which causes inaccurate tracking.

**Comment by markedagain** [comment]
this is actually a bug, since we add a country in 1 and that country breaks in every other campaign cause it also got added but with no defined amount

**Comment by mkendera** [comment]
It is implemented, will be published soon in next release

**Comment by lnikodem** [comment]
implemented in version 5.4.12.6
