### ISSUE TITLE
Add option to performance rewards rule to compute values from all campaigns

### ISSUE THREAD

**Issue by msvitek** [QualityUnit/pap-public#28]
add checkbox near rule 'compute commissions values from all campaigns'. Rule will be triggered only if new commission is created only to this exact campaign where is placed this rule, but commission of value (number of commissions) will be computed from all campaigns.

Customers in NEG-YBMOL-613, OMV-WNWKL-664, QRT-NFSKR-129 requested this option

**Comment by lnikodem** [comment]
implemented in 5.4.15.1
