### ISSUE TITLE
Automatic notification not active affiliates

### ISSUE THREAD

**Issue by jurajsim** [QualityUnit/pap-public#29]
I already reported this problem a while ago but nothing happen about it. 

As you know, lot of people join to be an affiliate of us merchant, but they don't do anything after first joining.

It's absolutely necessare a pluging or feature is build in that gives us the option to automatically send emails inform not active affiliates they should do more for the program or they get deleted from it. For example.

Message 1: First time informent they didn't create a click for 1 month or didn't loging for 1 month in the system. If they don't create a click or login the next month they will be removed from the system. 

Message 2: 1 day before removal last chance to create a click or to login to stay in the program. 

This option combined with the build in newsletter feature for affiliates makes sure we can motivate our affiliates better and keep only the real active affiliates in our systems. 

Please take this very serious as we all want a good system.

Regards,
Marc Wijnants

Creator Share4Profit affiliate program.

Message 1: First time informent they didn't create a click for 1 month or didn't loging for 1 month in the system. If they don't create a click or login the next month they will be removed from the system. 

Message 2: 1 day before removal last chance to create a click or to login to stay in the program. 

Make sure there is enough flexibility to send out messages before the actual removal. Plus time differentiation possibility.

**Comment by lnikodem** [comment]
new feature available from version 5.4.22
