### ISSUE TITLE
Magento plugin (post_affiliate_pro_connector) does not work with PAN

### ISSUE THREAD

**Issue by jurajsim** [QualityUnit/pap-public#30]
Magento plugin (post_affiliate_pro_connector) as downloaded via PAN does not actually work with PAN, but needs a hack in order to work.

It works fine with PAP because there is only 1 account to handle, but for PAN there are many different accounts.

For users of PAN they will need to manually insert needed to manually insert "PostAffTracker.setAccountId('XXX_MERCHANTS_ACCOUNT_ID_XXX');" in app/code/local/Mage/Pap/Block/saletracking.php for each merchant.

This is quite terrible when you have many merchants :-)

The above code was delivered by Brano / support and is working, just needs to make it use automatic-generated AccountID instead of manually-inserted.

So - please make it either look up the account ID based on the user-ID/Password supplied, as this would obviously be the most userfriendly + preferred solution.

Or alternatively if the above is technically to hard, then make it an editable field in the settings for the user to enter themselves.

Thank you very much :)

I will be glad to assist with testing it out, etc.

Clicks + impressions are correct tracked so its only the sales going to the default accountID under PAN, and not to the merchants accountID.

1) Using PAN for platform, download latest post_affiliate_pro_connector from index.php#Integration-Methods

2) Upload it to a Magento site following the instructions and enter merchant login/password.

3) Do test-purchases on that Magento-plaform, and see that all purchases are registered under the default account.

**Comment by mpullmann** [comment]
Toto je ten plugin, ktory podlieha Priacta copyrightu :turtle: takze zatvaram.

Bude treba vymazat z Gitu. Chystame sa spravit vlastny plugin.
