### ISSUE TITLE
Suggestion: Add the posibility to search Commissions for multiple IDs at once

### ISSUE THREAD

**Issue by msvitek** [QualityUnit/pap-public#35]
A customer UYV-YOUIR-478 requested an option to have the possibility to enter multiple commission IDs (those generated by system) in the advanced search in Commissions report and search for multiple there as it is currently possible with Order IDs.

See the screenshot, add the same option for commission "ID"s

![screen](https://cloud.githubusercontent.com/assets/10156080/8128926/29baa7b4-1104-11e5-9559-ac8f705ed5fd.png)

**Comment by lnikodem** [comment]
implemented in custom filters for operator "is in" and "is not in" in version 5.4.22
