### ISSUE TITLE
InterspireEmailMarketer works only with enabled curl

### ISSUE THREAD

**Issue by lnikodem** [QualityUnit/pap-public#36]
InterspireEmailMarketer gives error if curl is not enabled:

Fatal error:  Call to undefined function curl_init() in /plugins/InterspireEmailMarketer/Main.class.php on line 218

BAS-GMGEK-488

**Comment by sbusso** [comment]
it was missing curl + php5-curl. After installation it s working again.

**Comment by lnikodem** [comment]
fixed in 5.4.1.2
