### ISSUE TITLE
Suggestion: filter stats for more than one campaign

### ISSUE THREAD

**Issue by lnikodem** [QualityUnit/pap-public#47]
Now is in filter possible to filter stats only for one campaign, suggestion:
filter stats for more campaigns at once

**Comment by mkendera** [comment]
LFA-FJUMY-555

**Comment by mkendera** [comment]
LFA-FJUMY-555

**Comment by mkendera** [comment]
we are creating screen Top Campaigns for statistics from all campaigns: https://github.com/QualityUnit/pap-public/issues/58

**Comment by lnikodem** [comment]
also is possible to search by multiple values in custom filters for operators "is in" and "is not in" in version 5.4.22
