### ISSUE TITLE
suggestion: add clicks all (raw + unique) column to Daily reports grid

### ISSUE THREAD

**Issue by lnikodem** [QualityUnit/pap-public#50]
suggestion: add clicks all (raw + unique) column to Daily reports grid

**Comment by mkendera** [comment]
@lnikodem odkial je to suggestion?
duplicate of: https://github.com/QualityUnit/pap-issues/issues/469

**Comment by mkendera** [comment]
close: duplicate of: https://github.com/QualityUnit/pap-public/issues/49
