### ISSUE TITLE
Suggestion: Clicks should contain the URL of the page where the customer landed

### ISSUE THREAD

**Issue by msvitek** [QualityUnit/pap-public#51]
Customer in ZUI-CSIWJ-765 requested to be able to see in clicks, either in banner name or in data1 or data2 or some other field the URL of the page where the click tracking code executed and tracked the click.

> It is important there is still clear what page was visited even without a specific banner, When dynamically adding pages to sites you are not able to set a seperate banner per page. this is impossible. Affiliates still need to be able to see the page that was visited using their links. Please let the script show the url of the page that was visited. Example. Below is a dynamically generated page with an affiliate id implemented. When clicked no banner name shows up. Please pace the url for example under banner name then or below data1 or data2 or channel fields in lists. http://share4profit.com/video/video-from-vimeo-3/#wijna Regards, Marc Wijnants

**Comment by mkendera** [comment]
We don't plant to extend saved click params. But via custom plugin is possible to save url of page (where was located click tracking) to the data1 or data2 field of click.
