### ISSUE TITLE
Suggestion: Global header and footer for email templates

### ISSUE THREAD

**Issue by msvitek** [QualityUnit/pap-public#54]
ABS-BFNVA-698

1) Global header / footer for HTML emails
I wrote about that earlier. Now when you want to change a simple line in the footer of an email that is or should be the same on each email, you need to make changes in each email. If admin can define a global header and footer for HTML emails and just include the contents of that email in every email, one needs to to only one change.

**Comment by msvitek** [comment]
duplicate

**Comment by haldonclark** [comment]
Hi Martin,

Can't find the duplicate :)

**Comment by msvitek** [comment]
It has been reported in private repository by Martin Pullmann

**Comment by mkendera** [comment]
@haldonclark yes, this is not a duplicate, sorry for misunderstanding

**Comment by haldonclark** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/13968746/9539272/c59ae37e-4d4f-11e5-8f9e-470f6c40c029.jpg)

**Comment by haldonclark** [comment]
The screenshot illustrates more what I meant. Obviously I was not expressing myself properly. With this setup you only change the layout of ALL emails in one global template. For example, if you add a line to the footer of the email, such as a phone number, you do it once in the global header and footer and not 30 times in each email.

**Comment by mkenderaqu** [comment]
implemented since version 5.9.10.2
