### ISSUE TITLE
Suggestion: Categories for translation sources

### ISSUE THREAD

**Issue by msvitek** [QualityUnit/pap-public#55]
ABS-BFNVA-698

2) The translation snippets should be categorized for easier translation and for a better overview
Have a look at shopware solved this. It´s very neat! The text snippets are categorized and you can quickly browse the sections and find the snippets needed and translate them.

**Comment by jperdochqu** [comment]
Podla mna prio low low low. Mame search. Ked niekto preklada, tak zvycajne scenare su:
- prekladam vsetko zaradom
- chcem prelozit konkretnu frazu/frazy - ci uz preklad alebo korekcia defaultneho prekladu

Situacia, ze niekto si chce prelozit iba frazy z nejakej casti aplikacie, sa mi zda minimalne casta. Pri praci s prekladmi su momentalne prioritnejsie tasky (pridat kontext + diferencovat rovnaky string pre rozne kontexty).

**Comment by jperdochqu** [comment]
Our goal is to have translated whole application, not only several screens. This translating scenario isn't usual. Translators works mostly in two way:
- translate word by word whole application
- translate/change only string based on their search
I'm sorry, but we'll not implement this suggestion.
