### ISSUE TITLE
Add global CTR and SCR into daily report 

### ISSUE THREAD

**Issue by mprastiak** [QualityUnit/pap-public#56]
In daily reports there is a CTR Raw and CTR Unique, but there is no global CRT count. 
However global CTR is in Quick and Trends reports...
 
Also SCR is missing in the Daily report.. 
However you can see it banner manager or in Quick reports. 
Maybe it should be also added to Trends reports.

Previously there was this issue:
https://github.com/QualityUnit/pap-public/issues/49
which has been already imported in 5.4.12.6 version.

**Comment by lnikodem** [comment]
implemented in 5.4.12.8

**Comment by bnemecQU** [comment]
CTR je nahodene a frcii.
SCR v daily reporte chyba.

**Comment by mkendera** [comment]
implemented in 5.4.12.11
