### ISSUE TITLE
Dynamic link without banner ID (based on general affiliate link)

### ISSUE THREAD

**Issue by mkenderaqu** [QualityUnit/pap-public#59]
create single affiliate page (which is possible to add to menu)
content will be same as 'Dynamic link' (from banners list), but it have to work without banner id.
Base will be compared with general affiliate link, it means if inserted domain will be same as general affiliate link, linking method will be used same as general affiliate link, but if domain will be different, it will use click.php url.

**Comment by lnikodem** [comment]
implemented in version 5.4.24
