### ISSUE TITLE
PAP import function

### ISSUE THREAD

**Issue by haldonclark** [QualityUnit/pap-public#61]
In my opinion, the import function is more like a backup function than an import function. For this to have a significant value, the function should:
- import csv tables with every header name and sequence (not only one specified format)
- have the ability to map the columns of the csv file to be imported
- assign banner IDs automatically

**Comment by mkenderaqu** [comment]
since version 5.5.9.2, we have added import tool for affiliates to: Affiliate Manager
you can specify there fields which you have in your csv file.
Similar it is for import commissions.
