### ISSUE TITLE
General Affiliate Link

### ISSUE THREAD

**Issue by librero27** [QualityUnit/pap-public#62]
When use in Configuration > Affiliate linking method > Redirect links  and Save.

General Affiliate Link disappear from Affiliate Panel

**Comment by mkenderaqu** [comment]
Thanks for noticing us, we have reported this. 
It is hidden because in case of redirect links, general affiliate link is not nice it will looks like:
`http://URLtoPAP/scripts/click.php?a_aid={$refid}&desturl={$main_site_URL}`

**Comment by lnikodem** [comment]
added General Affiliate Link also fo Redirect links in 5.5.5.1.
