### ISSUE TITLE
Need to reorder the process so "Product ID Matching" check occurs prior to email issued to affiliate

### ISSUE THREAD

**Issue by auhoque** [QualityUnit/pap-public#63]
If you have any campaign with "Product ID Matching" (Merchant > Campaigns >Campaigns Manager > Edit Campaign > Product ID Matching https://d.pr/i/lbUnzS ) email is issued with wrong commission.

An example of production environment: 
-------------------------------------------
a. Email issued to affiliate with wrong commission $25.00 (https://d.pr/i/q54en3)
b. The correct and expected commission is $12.50 into commission grid (https://d.pr/i/n23msh)

How you can regenerate this
---------------------------------
1. If an SKU, as for example 'Product1' belongs to campaign 'CAMPAIGN-1' in **Product ID Matching** with 20% commission 
2. if the sales commission request submitted with 'CAMPAIGN-2' (where the commission percentage is 50%) campaign ID (I mean a_cid variable value)

The initial communication with Post Affiliate Pro submits this commissions as 'CAMPAIGN-2' campaign and it is recorded at 50% for a short time. Email is issued in this time and then product matching updates commissions.

I think, system need to reorder the process so product matching check occurs prior to email issued to affiliate
OR
When discovered the SKU for the email is part of a product matching setup to hold the email for 15 minutes

Let me know if you have a solution for this situation.

Thanks!

Arif

**Comment by mslastan** [comment]
We need further info and access to your Post Affiliate Pro installation from you to be able to investigate this problem of yours. I have emailed you directly.

**Comment by msvitek** [comment]
Customer was forcing ID of `CAMPAIGN-2` in his sale request and then manually amended the commission's campaign to `CAMPAIGN-1`
