### ISSUE TITLE
Commission settings will not show. Getting sqlstate error everytime. Help!

### ISSUE THREAD

**Issue by kbentley217** [QualityUnit/pap-public#8]
ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ct.cities' in 'field list' SQL: SELECT ct.commtypeid AS commtypeid,ct.rtype AS rtype,ct.rstatus AS rstatus,ct.name AS name,ct.approval AS approval,ct.code AS code,ct.recurrencepresetid AS recurrencepresetid,ct.countrycodes AS countrycodes,ct.campaignid AS campaignid,ct.parentcommtypeid AS parentcommtypeid,ct.zeroorderscommission AS zeroorderscommission,ct.savezerocommission AS savezerocommission,ct.cities AS cities,ct.locationtype AS locationtype FROM qu_pap_commissiontypes ct WHERE ct.campaignid = 'f3dbebe3' ORDER BY ct.rstatus DESC,ct.rtype ASC,ct.countrycodes ASC,ct.name ASC CODE: 1054

**Comment by msvitek** [comment]
This is not a bug, customer didn't process through update steps correctly. It has been dealt with in FBU-EZQAZ-538
