### ISSUE TITLE
Add the possibility to not hide "Parent affiliate" field in registration form

### ISSUE THREAD

**Issue by msvitek** [QualityUnit/pap-public#9]
Sometimes the customers wish for the new affiliates to be able to change/see who their parent will be so it would be good to have the option to not hide automatically the Parent ID field and in such case make sure that the Referral ID is displayed there and not the automatically generate user ID.

Reported in HEG-RJZSR-411

**Comment by lnikodem** [comment]
implemented in 5.4.12.8
